# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/xenial64"

    ubuntu.vm.provision "ansible" do |ansible|
        ansible.extra_vars = {
            ansible_python_interpreter: "/usr/bin/python3"
        }
    end
  end

  config.vm.define "centos" do |ubuntu|
    ubuntu.vm.box = "centos/7"
  end

  config.vm.box_check_update = false

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.compatibility_mode = "2.0"
  end
end
